language: swift
# xcode_project: SwiftMUD.xcodeproj # path to your xcodeproj folder
# xcode_scheme: SwiftMUDTests
# xcode_destination: platform=macOS
osx_image: xcode10

script:
  xcodebuild -scheme SwiftMUD -project SwiftMUD.xcodeproj build CODE_SIGNING_REQUIRED=NO

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  on:
    tags: true
